const vscode=require('vscode'),path=require('path'),fs=require('fs'),os=require('os'),cp=require('child_process'),http=require('http'),https=require('https');
const KW=['public','private','protected','internal','class','interface','enum','extends','implements','abstract','final','virtual','override','static','const','if','else','while','for','foreach','in','break','continue','return','new','this','super','latch','true','false','null','int','float','bool','string','char','void','List','Map','Set','import'];
const TYPES=new Set(['int','float','bool','string','char','void','List','Map','Set']);
const docs={println:['public native void println(value)','Writes a value followed by a newline.'],len:['public native int len(value)','Returns the size of a string, array, List, Map, or Set.'],latch:['latch(member_path, ...)','Declares mutation authority for object state.']};
const snippets={'public class':'public class ${1:Name} {\n\t$0\n}','constructor':'${1:ClassName}(${2}) {\n\t$0\n}','foreach':'foreach (${1:Type} ${2:item} in ${3:collection}) {\n\t$0\n}','for':'for (int ${1:i} = 0; ${1:i} < ${2:count}; ${1:i}++) {\n\t$0\n}','doc comment':'/// ${1:Summary}\n///\n/// @param ${2:name} ${3:Description}\n/// @return ${4:Description}','main':'int main() {\n\t$0\n\treturn 0;\n}','main args':'int main(string[] args) {\n\t$0\n\treturn 0;\n}'};
function exe(ctx){return path.join(ctx.extensionPath,'latch.exe')}
async function run(ctx,cmd){let e=vscode.window.activeTextEditor;if(!e)return;await e.document.save();if(cmd==='run'){cp.execFile(exe(ctx),['check',e.document.fileName],{windowsHide:true,cwd:path.dirname(e.document.fileName),timeout:10000},(err,stdout,stderr)=>{const ds=parseCompilerDiagnostic((stderr||'')+'\n'+(err&&stderr?'':stdout||''),e.document);diagnostics.set(e.document.uri,ds);if(err||ds.length){vscode.window.showErrorMessage('Latch found errors. Fix them before the program can run.');return}let t=vscode.window.createTerminal('Latch');t.show();t.sendText(`& "${exe(ctx)}" run "${e.document.fileName}"`);});return}let t=vscode.window.createTerminal('Latch');t.show();t.sendText(`& "${exe(ctx)}" ${cmd} "${e.document.fileName}"`);}
async function newProject(){const p=await vscode.window.showOpenDialog({canSelectFolders:true,canSelectFiles:false,canSelectMany:false,openLabel:'Create Here',title:'Choose where to create your Latch project'});if(!p?.length)return;const name=await vscode.window.showInputBox({prompt:'Latch project name',value:'MyLatchProject'});if(!name)return;const root=vscode.Uri.joinPath(p[0],name),src=vscode.Uri.joinPath(root,'src');await vscode.workspace.fs.createDirectory(src);await vscode.workspace.fs.createDirectory(vscode.Uri.joinPath(root,'build'));await vscode.workspace.fs.createDirectory(vscode.Uri.joinPath(root,'lib'));await vscode.workspace.fs.writeFile(vscode.Uri.joinPath(src,'main.lt'),Buffer.from('int main() {\n    println("Hello from Latch!");\n    return 0;\n}\n'));await vscode.workspace.fs.writeFile(vscode.Uri.joinPath(root,'latch.json'),Buffer.from(JSON.stringify({name,entry:'src/main.lt'},null,2)+'\n'));await vscode.commands.executeCommand('vscode.openFolder',root,false)}
async function newFile(){const u=await vscode.window.showSaveDialog({filters:{'Latch Source':['lt']}});if(!u)return;await vscode.workspace.fs.writeFile(u,Buffer.from('int main() {\n    return 0;\n}\n'));await vscode.window.showTextDocument(await vscode.workspace.openTextDocument(u))}
function docBefore(lines,i){let a=[];for(let j=i-1;j>=0;j--){let m=lines[j].match(/^\s*\/\/\/\s?(.*)$/);if(m){a.unshift(m[1]);continue}if(!lines[j].trim())continue;break}if(a.length)return a.join('\n').trim();let j=i-1;while(j>=0&&!lines[j].trim())j--;if(j>=0&&lines[j].includes('*/')){let b=[];for(;j>=0;j--){let line=lines[j];b.unshift(line.replace(/^\s*\/\*\*?\s?/, '').replace(/\*\/\s*$/, '').replace(/^\s*\*\s?/,''));if(line.includes('/**'))return b.join('\n').trim()}}return ''}
function scan(doc){const text=doc.getText(),lines=text.split(/\r?\n/),classes=new Map(),symbols=[];let current=null,depth=0;for(let i=0;i<lines.length;i++){let line=lines[i],before=depth;let cm=line.match(/^\s*(?:(public|private|protected|internal)\s+)?(?:(abstract|final)\s+)?class\s+(\w+)(?:\s+extends\s+(\w+))?/);if(cm){current={name:cm[3],mod:cm[1]||'internal',base:cm[4],members:[],line:i,doc:docBefore(lines,i)};classes.set(current.name,current);symbols.push({name:current.name,kind:'class',line:i,doc:current.doc,detail:`${current.mod} class ${current.name}${current.base?' extends '+current.base:''}`})}
if(current){let fm=line.match(/^\s*(?:(public|private|protected|internal)\s+)?(?:(final|static|const)\s+)?([A-Za-z_]\w*(?:<[^>]+>)?(?:\[\])?)\s+(\w+)\s*(?:=|;)/);if(fm){let x={name:fm[4],kind:'field',type:fm[3],mod:fm[1]||'private',line:i,doc:docBefore(lines,i),owner:current.name};current.members.push(x);symbols.push(x)}let mm=line.match(/^\s*(?:(public|private|protected|internal)\s+)?(?:(virtual|override|static|final|abstract)\s+)?([A-Za-z_]\w*(?:<[^>]+>)?(?:\[\])?)\s+(\w+)\s*\(([^)]*)\)/);if(mm&&!['if','for','while','foreach'].includes(mm[4])){let x={name:mm[4],kind:'method',type:mm[3],mod:mm[1]||'private',params:mm[5],line:i,doc:docBefore(lines,i),owner:current.name};current.members.push(x);symbols.push(x)}}
let vm=line.match(/\b([A-Za-z_]\w*(?:<[^>]+>)?(?:\[\])?)\s+(\w+)\s*(?==|;|,|\))/g);if(vm)for(const raw of vm){let m=raw.match(/([A-Za-z_]\w*(?:<[^>]+>)?(?:\[\])?)\s+(\w+)/);if(m&&!KW.includes(m[1]))symbols.push({name:m[2],kind:'variable',type:m[1],line:i,doc:''})}depth+=(line.match(/{/g)||[]).length-(line.match(/}/g)||[]).length;if(current&&depth<=0&&before>0)current=null}return {classes,symbols}}
async function projectIndex(){let all={classes:new Map(),symbols:[]};for(const d of vscode.workspace.textDocuments.filter(d=>d.languageId==='latch'))merge(all,scan(d));if(vscode.workspace.workspaceFolders){for(const u of await vscode.workspace.findFiles('**/*.lt','**/build/**',300)){let d=vscode.workspace.textDocuments.find(x=>x.uri.toString()===u.toString());if(!d)try{d=await vscode.workspace.openTextDocument(u)}catch{}if(d)merge(all,scan(d))}}return all}
function merge(a,b){for(const [k,v] of b.classes)a.classes.set(k,v);a.symbols.push(...b.symbols)}
function kind(k){return k==='class'?vscode.CompletionItemKind.Class:k==='method'?vscode.CompletionItemKind.Method:k==='field'?vscode.CompletionItemKind.Field:vscode.CompletionItemKind.Variable}
function word(doc,pos){let r=doc.getWordRangeAtPosition(pos);return r?doc.getText(r):''}
function mdFor(s){let m=new vscode.MarkdownString();m.appendCodeblock(s.detail||`${s.mod||''} ${s.type||''} ${s.name}${s.kind==='method'?'('+s.params+')':''}`.trim(),'latch');if(s.doc)m.appendMarkdown('\n'+s.doc.replace(/@param/g,'**Parameter**').replace(/@return/g,'**Returns**'));m.appendMarkdown(`\n\n**Kind:** ${s.kind}${s.owner?`  \n**Declared in:** ${s.owner}`:''}`);return m}

const diagnostics=vscode.languages.createDiagnosticCollection('latch');
const diagnosticTimers=new Map();
function parseCompilerDiagnostic(text,doc){
  const out=[]; const lines=String(text||'').split(/\r?\n/).filter(Boolean);
  for(const raw of lines){
    if(/Latch check passed\.?/.test(raw)) continue;
    let m=raw.match(/(?:Latch error:\s*)?(?:(.*?\.lt):)?(\d+):(\d+):\s*(.*)/);
    let line=0,col=0,msg=raw.replace(/^Latch error:\s*/,''),severity=vscode.DiagnosticSeverity.Error;
    if(m){line=Math.max(0,Number(m[2])-1);col=Math.max(0,Number(m[3])-1);msg=m[4]||msg;}
    else if(/^\s*-\s+/.test(raw)){msg=raw.replace(/^\s*-\s+/,'');}
    else if(!/Latch error:/i.test(raw)) continue;
    const end=Math.min(doc.lineAt(Math.min(line,doc.lineCount-1)).text.length, col+1);
    const d=new vscode.Diagnostic(new vscode.Range(line,col,line,Math.max(col+1,end)),msg,severity);
    d.source='Latch'; d.code='LATCH'; out.push(d);
  }
  return out;
}
async function checkDocument(ctx,doc){
  if(!doc || doc.languageId!=='latch' || doc.isClosed) return;
  const dir=path.dirname(doc.fileName), tmp=path.join(dir,`.latch-live-${process.pid}-${Date.now()}.lt`);
  try{
    await fs.promises.writeFile(tmp,doc.getText(),'utf8');
    cp.execFile(exe(ctx),['check',tmp],{windowsHide:true,cwd:dir,timeout:5000},(err,stdout,stderr)=>{
      fs.promises.unlink(tmp).catch(()=>{});
      const ds=parseCompilerDiagnostic((stderr||'')+'\n'+(err&&stderr?'':stdout||''),doc);
      diagnostics.set(doc.uri,ds);
    });
  }catch(e){ diagnostics.set(doc.uri,[new vscode.Diagnostic(new vscode.Range(0,0,0,1),`Live check failed: ${e.message}`,vscode.DiagnosticSeverity.Warning)]); }
}
function scheduleCheck(ctx,doc){
  if(!vscode.workspace.getConfiguration('latch').get('liveDiagnostics',true))return;
  const k=doc.uri.toString(); if(diagnosticTimers.has(k))clearTimeout(diagnosticTimers.get(k));
  diagnosticTimers.set(k,setTimeout(()=>{diagnosticTimers.delete(k);checkDocument(ctx,doc)},350));
}
function requestJson(url){return new Promise((resolve,reject)=>{try{const lib=url.startsWith('https:')?https:http;const req=lib.get(url,{headers:{'User-Agent':'Latch-VSCode'}},res=>{if(res.statusCode>=300&&res.statusCode<400&&res.headers.location){res.resume();return requestJson(new URL(res.headers.location,url).toString()).then(resolve,reject)}if(res.statusCode!==200){res.resume();return reject(new Error(`HTTP ${res.statusCode}`))}let b='';res.setEncoding('utf8');res.on('data',x=>b+=x);res.on('end',()=>{try{resolve(JSON.parse(b))}catch(e){reject(e)}})});req.setTimeout(5000,()=>req.destroy(new Error('timeout')));req.on('error',reject)}catch(e){reject(e)}})}
function downloadFile(url,dest){return new Promise((resolve,reject)=>{const go=u=>{const lib=u.startsWith('https:')?https:http;const req=lib.get(u,{headers:{'User-Agent':'Latch-VSCode'}},res=>{if(res.statusCode>=300&&res.statusCode<400&&res.headers.location){res.resume();return go(new URL(res.headers.location,u).toString())}if(res.statusCode!==200){res.resume();return reject(new Error(`HTTP ${res.statusCode}`))}const out=fs.createWriteStream(dest);res.pipe(out);out.on('finish',()=>out.close(()=>resolve(dest)));out.on('error',reject)});req.on('error',reject)};go(url)})}
async function installUpdate(ctx,m,latest){if(!m.downloadUrl)throw new Error('release manifest has no downloadUrl');const dest=path.join(os.tmpdir(),`latch-language-${latest}.vsix`);await vscode.window.withProgress({location:vscode.ProgressLocation.Notification,title:`Downloading Latch ${latest}...`},()=>downloadFile(m.downloadUrl,dest));await vscode.commands.executeCommand('workbench.extensions.installExtension',vscode.Uri.file(dest));const pick=await vscode.window.showInformationMessage(`Latch ${latest} installed. Reload VS Code to activate it.`,'Reload Now','Later');if(pick==='Reload Now')await vscode.commands.executeCommand('workbench.action.reloadWindow')}
function versionParts(v){return String(v).replace(/^v/,'').split(/[.-]/).map(x=>/^\d+$/.test(x)?Number(x):x)}
function newer(a,b){const A=versionParts(a),B=versionParts(b);for(let i=0;i<Math.max(A.length,B.length);i++){let x=A[i]??0,y=B[i]??0;if(typeof x==='number'&&typeof y==='number'){if(x!==y)return x>y}else if(String(x)!==String(y))return String(x)>String(y)}return false}
async function checkUpdates(ctx,manual=false){
  const cfg=vscode.workspace.getConfiguration('latch'); const url=cfg.get('releaseManifestUrl','');
  if(!url){if(manual)vscode.window.showInformationMessage('Latch update checking is ready, but no release manifest URL is configured yet. Set latch.releaseManifestUrl when Latch has a permanent release host.');return}
  try{const m=await requestJson(url);const current=ctx.extension.packageJSON.version,latest=m.version||m.latest;if(latest&&newer(latest,current)){const pick=await vscode.window.showInformationMessage(`Latch ${latest} is available (installed: ${current}).`,'Install Update','Release Page','Later');if(pick==='Install Update')await installUpdate(ctx,m,latest);else if(pick==='Release Page'&&m.notesUrl)vscode.env.openExternal(vscode.Uri.parse(m.notesUrl));}else if(manual)vscode.window.showInformationMessage(`Latch is up to date (${current}).`)}catch(e){if(manual)vscode.window.showWarningMessage(`Latch update check failed: ${e.message}`)}
}

function activate(ctx){ctx.subscriptions.push(vscode.commands.registerCommand('latch.newProject',newProject),vscode.commands.registerCommand('latch.newFile',newFile),vscode.commands.registerCommand('latch.run',()=>run(ctx,'run')),vscode.commands.registerCommand('latch.check',()=>run(ctx,'check')),vscode.commands.registerCommand('latch.docs',()=>vscode.env.openExternal(vscode.Uri.file(path.join(ctx.extensionPath,'docs','index.html')))),vscode.commands.registerCommand('latch.enableIcons',async()=>vscode.workspace.getConfiguration('workbench').update('iconTheme','latch-lt-icons',vscode.ConfigurationTarget.Global)),vscode.commands.registerCommand('latch.checkUpdates',()=>checkUpdates(ctx,true)));
ctx.subscriptions.push(diagnostics,vscode.workspace.onDidChangeTextDocument(e=>{if(e.document.languageId==='latch')scheduleCheck(ctx,e.document)}),vscode.workspace.onDidOpenTextDocument(d=>{if(d.languageId==='latch')scheduleCheck(ctx,d)}),vscode.workspace.onDidCloseTextDocument(d=>diagnostics.delete(d.uri)));
for(const d of vscode.workspace.textDocuments)if(d.languageId==='latch')scheduleCheck(ctx,d);
if(vscode.workspace.getConfiguration('latch').get('autoCheckUpdates',true))setTimeout(()=>checkUpdates(ctx,false),1500);
ctx.subscriptions.push(vscode.languages.registerCompletionItemProvider('latch',{async provideCompletionItems(doc,pos){const idx=await projectIndex(),line=doc.lineAt(pos.line).text.slice(0,pos.character),out=[];let mm=line.match(/(\w+)\.\w*$/);if(mm){let vs=scan(doc).symbols.filter(s=>s.name===mm[1]&&s.type),v=vs.at(-1),c=v&&idx.classes.get(v.type);if(c)for(const s of c.members)if(s.mod!=='private'){let i=new vscode.CompletionItem(s.name,kind(s.kind));i.detail=`${s.mod} ${s.type||''} ${s.name}`;i.documentation=s.doc;out.push(i)}return out}for(const w of KW){let i=new vscode.CompletionItem(w,TYPES.has(w)?vscode.CompletionItemKind.TypeParameter:vscode.CompletionItemKind.Keyword);i.sortText='0'+w;out.push(i)}for(const s of idx.symbols){let i=new vscode.CompletionItem(s.name,kind(s.kind));i.detail=s.detail||`${s.type||''} ${s.kind}`;i.documentation=s.doc;out.push(i)}for(const [n,b] of Object.entries(snippets)){let i=new vscode.CompletionItem(n,vscode.CompletionItemKind.Snippet);i.insertText=new vscode.SnippetString(b);i.sortText='1'+n;out.push(i)}return out}},'.abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'));
ctx.subscriptions.push(vscode.languages.registerHoverProvider('latch',{async provideHover(doc,pos){let w=word(doc,pos);if(docs[w]){let m=new vscode.MarkdownString();m.appendCodeblock(docs[w][0],'latch');m.appendMarkdown(docs[w][1]);return new vscode.Hover(m)}let idx=await projectIndex(),s=idx.symbols.filter(x=>x.name===w).at(-1);return s?new vscode.Hover(mdFor(s)):undefined}}));
ctx.subscriptions.push(vscode.languages.registerDefinitionProvider('latch',{async provideDefinition(doc,pos){let w=word(doc,pos),idx=await projectIndex();for(const d of vscode.workspace.textDocuments.filter(d=>d.languageId==='latch')){let sc=scan(d),s=sc.symbols.find(x=>x.name===w);if(s)return new vscode.Location(d.uri,new vscode.Position(s.line,Math.max(0,d.lineAt(s.line).text.indexOf(w))))}return undefined}}));
const legend=new vscode.SemanticTokensLegend(['keyword','type','class','property','method','variable']);ctx.subscriptions.push(vscode.languages.registerDocumentSemanticTokensProvider('latch',{provideDocumentSemanticTokens(doc){let b=new vscode.SemanticTokensBuilder(legend),lines=doc.getText().split(/\r?\n/),prefixes=KW.filter(x=>x.length>1);for(let ln=0;ln<lines.length;ln++){let line=lines[ln];for(const m of line.matchAll(/\b[A-Za-z_]\w*\b/g)){let w=m[0];if(KW.includes(w))b.push(ln,m.index,w.length,TYPES.has(w)?1:0,0);else if(prefixes.some(k=>k.startsWith(w)))b.push(ln,m.index,w.length,0,0)} }return b.build()}},legend));}
exports.activate=activate;exports.deactivate=()=>{};
